@startuml Architecture
[Angular Frontend] as angular
[React Native\n Mobile App] as mobile
[Java\n neighbourly-auth-service] as auth
[Java\n neighbourly-user-service] as user
[Java\n neighbourly-gateway-service] as gateway
[Java\n neighbourly-community-service] as community
[Java\n neighbourly-marketplace-service] as marketplace
[Java\n neighbourly-conversation-service] as conversation


database "users" as user_db
database "marketplace" as marketplace_db 
database "conversations" as conversation_db
database "community" as community_db
database "cloudinary" as cloudinary_db



user --> user_db

conversation --> conversation_db
marketplace --> marketplace_db
community --> community_db
marketplace --> cloudinary_db
community --> cloudinary_db


gateway --> user
gateway --> marketplace
gateway --> conversation
gateway --> community


angular --> gateway
mobile --> gateway





@enduml

