@startuml neighborly-class
class Member {
    int memberId
    String firstName
    String lastName
    String email
    String password
    String phone
    String community
    String flatNo
    Date memberSince
    Date lastLogin
    Item[] items
    Conversation[] conversations   

}

class Item {
    int itemId
    String title
    String description
    double price
    Category category
    community community
    Member seller
    Condition Condition
    Photo[] photos
    boolean active
}


class Property{
 PROPERTY_FOR for
 PROPERTY_TYPE type
 BHK_TYPE bhkType
 Photo[] photos
 String description
 String builtUp_area
 String carpet_area
 Facing facing
 FLOOR floor
 FLOOR totalFloor
 PROPERTY_AGE age
 String expectedPrice
 boolean priceNegotiable
 boolean currentlyUnderLoan
 FURNISHING furnishing
 PARKING parking
 Date availableFrom
 WATER_SUPPLY waterSupply
 int bathrooms
 int balconies
 POWER_BACKUP powerBackup
 ANSWER haveYouPaidPropertyTax
 ANSWER doYouHaveOccupancyCertificate
 ANSWER doYouHaveSaleDeed
 SCHEDULE scheduleVisit

}


enum ANSWER{
    YES
    NO
    DONT_KNOW
}




enum POWER_BACKUP{
    FULL
    PARTIAL
    NONE
}


enum WATER_SUPPLY{
    CORPORATION
    BOREWELL
    BOTH
}

class Location{
    String city
    String locality
    String street
    String landmark

}

enum PARKING{
    CAR
    BIKE
    BOTH
    NONE
}

enum FURNISHING{
    FULLY_FURNISHED
    SEMI_FURNISHED
    UN_FURNISHED
}

enum PROPERTY_AGE{
    UNDER_CONSTRUCTION
    LESS_THAN_A_YEAR
    1_TO_3_YEARS
    3_TO_5_YEARS
    5_TO_10_YEARS
    MORE_THAN_10_YEARS
}

enum FLOOR{
    GROUND
    1
    2
    3
    4
}

enum FACING{
    NORTH
    SOUTH
    EAST
    WEST
    NORTH_EAST
    SOUTH_EAST
    NOTH_WEST
    SOUTH_WEST
    DONT_KNOW
}

enum BHK_TYPE{
    1RK
    2BHK
    3BHK
    4BHK
    4+BHK
}


enum PROPERTY_TYPE{
    FLAT
    HOUSE
}

enum PROPERTY_FOR{
    SALE
    RENT
}

class Photo {
    int photoId
    String url
    String description
}

class Message{
    int messageId
    String content
    Member sender
    Member receiver
    Date sentAt
    Date readAt
}

class Conversation {
    int  conversationId
    Message[] messages
    Member[] participants
}

enum Category {
    VEHICLES
    PROPERTIES
    BOOKS
    CLOTHING
    JEWELLERY
    TOYS
    ELECTRONICS
    FURNITURE
    CLOTHING
    TOYS_AND_GAMES
    BABY_PRODUCTS
    BOOKS
    OTHER
    FOOD
    GROCERIES
    GARDEN_AND_OUTDOORS
    PET_SUPPLIES
    STATIONARY
}
enum community {
    Marina Skies
    Rainbow Vistas Rock Garden
    Rainbow Vistas
}

enum ItemStatus {
    AVAILABLE
    SOLD
    REMOVED
}


enum Condition {
    NEW
    Used_LIKE_NEW
    USED_GOOD
    USED_FAIR
}


Member "1" -- "0..*" Item : sells/buy/view
Member "1" -- "1" community :  lives in
Item "1" -- "1" Category : belongs to
Item "1" -- "1" community : belongs to
Item "1" -- "1" Condition : is in
Item "1" -- "0..*" Photo : has
Item "1" -- "1" ItemStatus : is in
Conversation "1" -- "1..*" Message : has
Conversation "1" -- "2" Member : has

Property "1" -- "0..*" Photo : has
Property "1" -- "1" Location : has
Property "1" -- "1" PROPERTY_FOR : is for
Property "1" -- "1" PROPERTY_TYPE : is of type
Property "1" -- "1" BHK_TYPE : is of type
Property "1" -- "1" FLOOR : is on
Property "1" -- "1" FACING : is of
Property "1" -- "1" PROPERTY_AGE : is of
Property "1" -- "1" FURNISHING : is of
Property "1" -- "1" PARKING : is of
Property "1" -- "1" WATER_SUPPLY : is of
Property "1" -- "1" POWER_BACKUP : is of
Property "1" -- "1" ANSWER : is of
@enduml
